exports.ORDER_PREPARING = 'ORDER_PREPARING';
exports.ORDER_SHIPPING = 'ORDER_SHIPPING';
exports.ORDER_SUCCESS = 'ORDER_SUCCESS';

exports.MODE_ADMIN = 'MODE_ADMIN';
exports.MODE_USER = 'MODE_USER';
